language: node_js
node_js:
- 14
cache: yarn
jobs:
  include:
  - stage: Build
    name: Build SDK
    script:
      - yarn build:prod
  - stage: Test
    name: Run test cases
    script:
      - yarn test
  - stage: NPM Release
    name: Release new version of SDK
    node_js: lts/*
    script: echo "Deploying to npm"
    before_deploy:
      - yarn build:prod
    deploy:
      provider: script
      skip_cleanup: true
      script: yarn && npx semantic-release
      on:
        branch:
          - master
          - next
          - alpha
          - beta 
notifications:
  slack: unbxd:6lCkwyhlkp87V1vvR4ZSe8OL