name: searchJsLibrary
on:
    pull_request:
    push:
        branches:
            - master
            - next
            - alpha
            - beta 
env:
    CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
defaults:
    run:
        shell: bash
jobs:
    test:
        name: Test 🧪
        runs-on: ubuntu-latest
        steps:
            - name: Pre-reqs
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 15

            - name: Check Cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Test
              run: yarn test

    build:
        name: Build ⚙️
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Pre-reqs
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 15

            - name: Check Cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Build
              run: yarn build:prod
    publish:
        name: Publish 🚀
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Pre-reqs
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 15
            - name: Check Cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Semantic Release
              uses: cycjimmy/semantic-release-action@v2.5.3